name: ReegoCraft
version: ${project.version}
main: dev.jayjaytee.reegocraft.ReegoCraft
api-version: 1.15
depend: [HolographicDisplays,NBTAPI]
authors: [JAYJAYTEE]

commands:
  crate:
    description: Gives someone a crate.
  reegoitems:
    description: Gives you the custom items.
  rename:
    description: Renames a item for you.
  upgrade:
    description: Upgrades a item for you.
  save:
    description: Saves the player file.
  reset:
    description: Resets the player's file.